version: "3.8"
services:
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    depends_on:
      - server

  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: swarraaa
      MONGO_INITDB_ROOT_PASSWORD: swarraaa
    ports:
      - "27017:27017"
